CREATE TABLE OISEAU (ID INTEGER NOT NULL, OISEAU_TYPE VARCHAR(31), NBSERRES INTEGER, CIBLE_ID INTEGER, NBPLUMES INTEGER, PRIMARY KEY (ID))
ALTER TABLE OISEAU ADD CONSTRAINT FK_OISEAU_CIBLE_ID FOREIGN KEY (CIBLE_ID) REFERENCES OISEAU (ID)
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
